//
// Created by konrad on 16.05.17.
//

#ifndef MULTHITHREADINGCONSUMERSNPRODUCERS_QUEUESTRUCTURE_H
#define MULTHITHREADINGCONSUMERSNPRODUCERS_QUEUESTRUCTURE_H


class QueueStructure {

};


#endif //MULTHITHREADINGCONSUMERSNPRODUCERS_QUEUESTRUCTURE_H
